from pydantic import BaseModel, ConfigDict
from typing import List, Optional
from datetime import date, datetime

class PuutarhassaViljelynTarkoitusBase(BaseModel):
    viljely_nro: int
    hankintaID: int
    puutarhassa_viljelyn_tarkoitus: Optional[str] = None
    puutarhassa_viljelyn_tarkenne: Optional[str] = None

class PuutarhassaViljelynTarkoitusCreate(BaseModel):
    hankintaID: int
    puutarhassa_viljelyn_tarkoitus: Optional[str] = None
    puutarhassa_viljelyn_tarkenne: Optional[str] = None
    viljely_nro: Optional[int] = None  # excluded from INSERT; auto-generated by the DB


class PuutarhassaViljelynTarkoitus(PuutarhassaViljelynTarkoitusBase):
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    model_config = ConfigDict(from_attributes=True)

class PuutarhassaViljelynTarkoitusPage(BaseModel):
    items: List[PuutarhassaViljelynTarkoitus]
    total: int
    page: int
    page_size: int
    pages: int
