"""Add plant tag columns to hankintatiedot

Revision ID: 1c2bb35e25bf
Revises: ff5a2231b038
Create Date: 2026-06-30 15:29:49.589629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c2bb35e25bf'
down_revision: Union[str, Sequence[str], None] = 'ff5a2231b038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_hankintatiedot')
    with op.batch_alter_table('hankintatiedot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_en', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tag_fi', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('why_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('why_fi', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('time_definition_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('time_definition_fi', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_hankintatiedot_hankintanumero'), ['hankintanumero'])

    with op.batch_alter_table('maaritysmerkinta', schema=None) as batch_op:
        batch_op.alter_column('uus_maarityspvm',
               existing_type=sa.DATE(),
               type_=app.models.base.SafeDate(),
               existing_nullable=True)

    with op.batch_alter_table('naytetietoja', schema=None) as batch_op:
        batch_op.alter_column('uus_naytteen_paivays',
               existing_type=sa.DATE(),
               type_=app.models.base.SafeDate(),
               existing_nullable=True)

    with op.batch_alter_table('testi', schema=None) as batch_op:
        batch_op.alter_column('uuspvm',
               existing_type=sa.DATE(),
               type_=app.models.base.SafeDate(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')

    with op.batch_alter_table('testi', schema=None) as batch_op:
        batch_op.alter_column('uuspvm',
               existing_type=app.models.base.SafeDate(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('naytetietoja', schema=None) as batch_op:
        batch_op.alter_column('uus_naytteen_paivays',
               existing_type=app.models.base.SafeDate(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('maaritysmerkinta', schema=None) as batch_op:
        batch_op.alter_column('uus_maarityspvm',
               existing_type=app.models.base.SafeDate(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('hankintatiedot', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_hankintatiedot_hankintanumero'), type_='unique')
        batch_op.drop_column('time_definition_fi')
        batch_op.drop_column('time_definition_en')
        batch_op.drop_column('why_fi')
        batch_op.drop_column('why_en')
        batch_op.drop_column('tag_fi')
        batch_op.drop_column('tag_en')

    op.create_table('_alembic_tmp_hankintatiedot',
    sa.Column('hankintaID', sa.INTEGER(), nullable=False),
    sa.Column('hankintanumero', sa.VARCHAR(length=255), nullable=True),
    sa.Column('saapumispvm', sa.VARCHAR(length=255), nullable=True),
    sa.Column('hankintanimi', sa.VARCHAR(length=255), nullable=True),
    sa.Column('millaisena_saatu', sa.VARCHAR(length=255), nullable=True),
    sa.Column('erikoiskokoelma_oma_puutarha', sa.VARCHAR(length=255), nullable=True),
    sa.Column('materiaalin_arvo', sa.VARCHAR(length=255), nullable=True),
    sa.Column('lisatiedot', sa.VARCHAR(length=255), nullable=True),
    sa.Column('jarjestysnro', sa.VARCHAR(length=255), nullable=True),
    sa.Column('vuosi', sa.VARCHAR(length=255), nullable=True),
    sa.Column('lisaysPVM', sa.VARCHAR(length=255), nullable=True),
    sa.Column('lisayshistoria', sa.TEXT(), nullable=True),
    sa.Column('kasvin_huomautuksia', sa.TEXT(), nullable=True),
    sa.Column('hankintahistoria', sa.TEXT(), nullable=True),
    sa.Column('taksonin_nro', sa.INTEGER(), nullable=False),
    sa.Column('lahettajanro', sa.INTEGER(), nullable=False),
    sa.Column('put', sa.INTEGER(), nullable=True),
    sa.Column('puttia', sa.VARCHAR(length=255), nullable=True),
    sa.Column('numero', sa.INTEGER(), nullable=True),
    sa.Column('vuosiluku', sa.INTEGER(), nullable=True),
    sa.Column('heimo', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lahettajanro'], ['lahettaja.lahettajanro'], name=op.f('hankintatiedot_ibfk_2')),
    sa.ForeignKeyConstraint(['taksonin_nro'], ['taksoni.taksonin_nro'], name=op.f('hankintatiedot_ibfk_1')),
    sa.PrimaryKeyConstraint('hankintaID'),
    sa.UniqueConstraint('hankintanumero', name=op.f('uq_hankintatiedot_hankintanumero'))
    )
    # ### end Alembic commands ###
