"""Add plant tag columns to hankintatiedot

Revision ID: 1c2bb35e25bf
Revises: ff5a2231b038
Create Date: 2026-06-30 15:29:49.589629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision: str = '1c2bb35e25bf'
down_revision: Union[str, Sequence[str], None] = 'ff5a2231b038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hankintatiedot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_en', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tag_fi', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('why_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('why_fi', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('time_definition_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('time_definition_fi', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_hankintatiedot_hankintanumero'), ['hankintanumero'])

    with op.batch_alter_table('maaritysmerkinta', schema=None) as batch_op:
        batch_op.alter_column('uus_maarityspvm',
               existing_type=sa.DATE(),
               type_=app.models.base.SafeDate(),
               existing_nullable=True)

    with op.batch_alter_table('naytetietoja', schema=None) as batch_op:
        batch_op.alter_column('uus_naytteen_paivays',
               existing_type=sa.DATE(),
               type_=app.models.base.SafeDate(),
               existing_nullable=True)

    with op.batch_alter_table('testi', schema=None) as batch_op:
        batch_op.alter_column('uuspvm',
               existing_type=sa.DATE(),
               type_=app.models.base.SafeDate(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')

    with op.batch_alter_table('testi', schema=None) as batch_op:
        batch_op.alter_column('uuspvm',
               existing_type=app.models.base.SafeDate(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('naytetietoja', schema=None) as batch_op:
        batch_op.alter_column('uus_naytteen_paivays',
               existing_type=app.models.base.SafeDate(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('maaritysmerkinta', schema=None) as batch_op:
        batch_op.alter_column('uus_maarityspvm',
               existing_type=app.models.base.SafeDate(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('hankintatiedot', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_hankintatiedot_hankintanumero'), type_='unique')
        batch_op.drop_column('time_definition_fi')
        batch_op.drop_column('time_definition_en')
        batch_op.drop_column('why_fi')
        batch_op.drop_column('why_en')
        batch_op.drop_column('tag_fi')
        batch_op.drop_column('tag_en')

    # ### end Alembic commands ###
