"""Add created_at and updated_at using batch mode

Revision ID: b10d57f459ef
Revises: f8985dffebf3
Create Date: 2026-06-20 02:06:52.987920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b10d57f459ef'
down_revision: Union[str, Sequence[str], None] = 'f8985dffebf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_alkuperaa_koskevat_tiedot', if_exists=True)
    with op.batch_alter_table('alkuperaa_koskevat_tiedot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.create_index('IDX_Alkuperaa_koskevat_tiedot1', ['hankintaID'], unique=False)
        batch_op.create_foreign_key('alkuperaa_koskevat_tiedot_ibfk_1', 'hankintatiedot', ['hankintaID'], ['hankintaID'])

    with op.batch_alter_table('alkuperainen_kasvupaikka', schema=None) as batch_op:
        batch_op.create_index('IDX_Alkuperainen_kasvupaikka1', ['taksonin_nro'], unique=False)
        batch_op.create_index('IDX_Alkuperainen_kasvupaikka2', ['viitenro'], unique=False)
        batch_op.create_foreign_key('alkuperainen_kasvupaikka_ibfk_1', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])
        batch_op.create_foreign_key('alkuperainen_kasvupaikka_ibfk_2', 'viite', ['viitenro'], ['viitenro'])

    with op.batch_alter_table('hankintatiedot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.create_index('IDX_Hankintatiedot1', ['taksonin_nro'], unique=False)
        batch_op.create_index('IDX_Hankintatiedot2', ['lahettajanro'], unique=False)
        batch_op.create_index('ix_hankintatiedot_hankintanumero', ['hankintanumero'], unique=True)
        batch_op.create_foreign_key('hankintatiedot_ibfk_1', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])
        batch_op.create_foreign_key('hankintatiedot_ibfk_2', 'lahettaja', ['lahettajanro'], ['lahettajanro'])

    with op.batch_alter_table('kansainvaliset_sopimukset', schema=None) as batch_op:
        batch_op.create_index('IDX_Kansainvaliset_Sopimukset1', ['taksonin_nro'], unique=False)
        batch_op.create_index('IDX_Kansainvaliset_Sopimukset2', ['viitenro'], unique=False)
        batch_op.create_foreign_key('kansainvaliset_sopimukset_ibfk_1', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])
        batch_op.create_foreign_key('kansainvaliset_sopimukset_ibfk_2', 'viite', ['viitenro'], ['viitenro'])

    with op.batch_alter_table('kasvatustietoja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.create_index('IDX_Kasvatustietoja1', ['hankintaID'], unique=False)
        batch_op.create_foreign_key('kasvatustietoja_ibfk_1', 'hankintatiedot', ['hankintaID'], ['hankintaID'])

    with op.batch_alter_table('kasvin_kayttotarkoitus', schema=None) as batch_op:
        batch_op.create_index('IDX_Kasvin_kayttotarkoitus1', ['taksonin_nro'], unique=False)
        batch_op.create_index('IDX_Kasvin_kayttotarkoitus2', ['viitenro'], unique=False)
        batch_op.create_foreign_key('kasvin_kayttotarkoitus_ibfk_2', 'viite', ['viitenro'], ['viitenro'])
        batch_op.create_foreign_key('kasvin_kayttotarkoitus_ibfk_1', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])

    with op.batch_alter_table('kayttajatiedot', schema=None) as batch_op:
        batch_op.create_index('kayttajan_tunnus', ['kayttajan_tunnus'], unique=True)

    with op.batch_alter_table('lahettaja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    with op.batch_alter_table('lukitut_taulut', schema=None) as batch_op:
        batch_op.create_index('avainkentta', ['avainkentta'], unique=True)

    with op.batch_alter_table('maailman_levinneisyysalue', schema=None) as batch_op:
        batch_op.create_index('IDX_Maailman_Levinneisyysalue1', ['taksonin_nro'], unique=False)
        batch_op.create_foreign_key('maailman_levinneisyysalue_ibfk_1', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])

    with op.batch_alter_table('maaritysmerkinta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.alter_column('uus_maarityspvm',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.create_index('IDX_Maaritysmerkinta1', ['hankintaID'], unique=False)
        batch_op.create_foreign_key('maaritysmerkinta_ibfk_1', 'hankintatiedot', ['hankintaID'], ['hankintaID'])

    with op.batch_alter_table('muunkielinen_nimi', schema=None) as batch_op:
        batch_op.create_index('IDX_Muunkielinen_nimi1', ['taksonin_nro'], unique=False)
        batch_op.create_index('IDX_Muunkielinen_nimi2', ['viitenro'], unique=False)
        batch_op.create_foreign_key('muunkielinen_nimi_ibfk_1', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])
        batch_op.create_foreign_key('muunkielinen_nimi_ibfk_2', 'viite', ['viitenro'], ['viitenro'])

    with op.batch_alter_table('naytetieto', schema=None) as batch_op:
        batch_op.create_index('IDX_Naytetieto1', ['taksonin_nro'], unique=False)
        batch_op.create_index('IDX_Naytetieto2', ['viitenro'], unique=False)
        batch_op.create_foreign_key('naytetieto_ibfk_2', 'viite', ['viitenro'], ['viitenro'])
        batch_op.create_foreign_key('naytetieto_ibfk_1', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])

    with op.batch_alter_table('naytetietoja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.alter_column('uus_naytteen_paivays',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.create_index('IDX_Naytetietoja1', ['hankintaID'], unique=False)
        batch_op.create_foreign_key('naytetietoja_ibfk_1', 'hankintatiedot', ['hankintaID'], ['hankintaID'])

    with op.batch_alter_table('osastopaikka', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.alter_column('osaston_numero',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.create_index('IDX_Osastopaikka1', ['hankintaID'], unique=False)
        batch_op.create_foreign_key('osastopaikka_ibfk_1', 'hankintatiedot', ['hankintaID'], ['hankintaID'])

    with op.batch_alter_table('puutarhassa_viljelyn_tarkoitus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.alter_column('viljely_nro',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.create_index('IDX_Puutarhassa_viljelyn_tarkoitus1', ['hankintaID'], unique=False)
        batch_op.create_foreign_key('puutarhassa_viljelyn_tarkoitus_ibfk_1', 'hankintatiedot', ['hankintaID'], ['hankintaID'])

    with op.batch_alter_table('sijoituspaikka', schema=None) as batch_op:
        batch_op.create_index('IDX_Sijoituspaikka1', ['osaston_numero'], unique=False)
        batch_op.create_foreign_key('sijoituspaikka_ibfk_1', 'osastopaikka', ['osaston_numero'], ['osaston_numero'])

    with op.batch_alter_table('suomalainen_kasvupaikka', schema=None) as batch_op:
        batch_op.create_index('IDX_Suomalainen_kasvupaikka1', ['taksonin_nro'], unique=False)
        batch_op.create_index('IDX_Suomalainen_kasvupaikka2', ['viitenro'], unique=False)
        batch_op.create_foreign_key('suomalainen_kasvupaikka_ibfk_1', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])
        batch_op.create_foreign_key('suomalainen_kasvupaikka_ibfk_2', 'viite', ['viitenro'], ['viitenro'])

    with op.batch_alter_table('suomalainen_levinneisyysalue', schema=None) as batch_op:
        batch_op.create_index('IDX_Suomalainen_Levinneisyysalue1', ['taksonin_nro'], unique=False)
        batch_op.create_index('IDX_Suomalainen_Levinneisyysalue2', ['viitenro'], unique=False)
        batch_op.create_foreign_key('suomalainen_levinneisyysalue_ibfk_2', 'viite', ['viitenro'], ['viitenro'])
        batch_op.create_foreign_key('suomalainen_levinneisyysalue_ibfk_1', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])

    with op.batch_alter_table('suunniteltu_kasvupaikka', schema=None) as batch_op:
        batch_op.create_index('IDX_Suunniteltu_kasvupaikka1', ['taksonin_nro'], unique=False)
        batch_op.create_foreign_key('suunniteltu_kasvupaikka_ibfk_1', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])

    with op.batch_alter_table('synonyymi', schema=None) as batch_op:
        batch_op.create_index('IDX_Synonyymi1', ['taksonin_nro'], unique=False)
        batch_op.create_index('IDX_Synonyymi2', ['viitenro'], unique=False)
        batch_op.create_foreign_key('synonyymi_ibfk_1', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])
        batch_op.create_foreign_key('synonyymi_ibfk_2', 'viite', ['viitenro'], ['viitenro'])

    with op.batch_alter_table('taksoni', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.create_index('IDX_Taksoni1', ['jarjestysnumero'], unique=False)
        batch_op.create_index('IDX_Taksoni2', ['viitenro'], unique=False)
        batch_op.create_foreign_key('taksoni_ibfk_2', 'viite', ['viitenro'], ['viitenro'])
        batch_op.create_foreign_key('taksoni_ibfk_1', 'heimo', ['jarjestysnumero'], ['jarjestysnumero'])

    with op.batch_alter_table('taksonin_lappu', schema=None) as batch_op:
        batch_op.create_index('IDX_Taksonin_lappu1', ['taksonin_nro'], unique=False)
        batch_op.create_foreign_key('taksonin_lappu_ibfk_1', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])

    with op.batch_alter_table('taksonin_viljelytiedot', schema=None) as batch_op:
        batch_op.create_index('IDX_Taksonin_viljelytiedot1', ['taksonin_nro'], unique=False)
        batch_op.create_foreign_key('taksonin_viljelytiedot_ibfk_1', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])

    with op.batch_alter_table('tarkastusmerkinta', schema=None) as batch_op:
        batch_op.alter_column('uus_tarkastuspvm',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_index('IDX_Tarkastusmerkinta1', ['sijoituspaikan_nro'], unique=False)
        batch_op.create_foreign_key('tarkastusmerkinta_ibfk_1', 'sijoituspaikka', ['sijoituspaikan_nro'], ['sijoituspaikan_nro'])

    with op.batch_alter_table('toimenpide', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.alter_column('uus_pvm',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_index('IDX_Toimenpide1', ['hankintaID'], unique=False)
        batch_op.create_foreign_key('toimenpide_ibfk_1', 'hankintatiedot', ['hankintaID'], ['hankintaID'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('ymparistoindikaattoriluonne', schema=None) as batch_op:
        batch_op.create_index('IDX_Ymparistoindikaattoriluonne1', ['taksonin_nro'], unique=False)
        batch_op.create_index('IDX_Ymparistoindikaattoriluonne2', ['viitenro'], unique=False)
        batch_op.create_foreign_key('ymparistoindikaattoriluonne_ibfk_1', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])
        batch_op.create_foreign_key('ymparistoindikaattoriluonne_ibfk_2', 'viite', ['viitenro'], ['viitenro'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ymparistoindikaattoriluonne', schema=None) as batch_op:
        batch_op.drop_constraint('ymparistoindikaattoriluonne_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('ymparistoindikaattoriluonne_ibfk_1', type_='foreignkey')
        batch_op.drop_index('IDX_Ymparistoindikaattoriluonne2')
        batch_op.drop_index('IDX_Ymparistoindikaattoriluonne1')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('toimenpide', schema=None) as batch_op:
        batch_op.drop_constraint('toimenpide_ibfk_1', type_='foreignkey')
        batch_op.drop_index('IDX_Toimenpide1')
        batch_op.alter_column('uus_pvm',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('tarkastusmerkinta', schema=None) as batch_op:
        batch_op.drop_constraint('tarkastusmerkinta_ibfk_1', type_='foreignkey')
        batch_op.drop_index('IDX_Tarkastusmerkinta1')
        batch_op.alter_column('uus_tarkastuspvm',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('taksonin_viljelytiedot', schema=None) as batch_op:
        batch_op.drop_constraint('taksonin_viljelytiedot_ibfk_1', type_='foreignkey')
        batch_op.drop_index('IDX_Taksonin_viljelytiedot1')

    with op.batch_alter_table('taksonin_lappu', schema=None) as batch_op:
        batch_op.drop_constraint('taksonin_lappu_ibfk_1', type_='foreignkey')
        batch_op.drop_index('IDX_Taksonin_lappu1')

    with op.batch_alter_table('taksoni', schema=None) as batch_op:
        batch_op.drop_constraint('taksoni_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('taksoni_ibfk_2', type_='foreignkey')
        batch_op.drop_index('IDX_Taksoni2')
        batch_op.drop_index('IDX_Taksoni1')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('synonyymi', schema=None) as batch_op:
        batch_op.drop_constraint('synonyymi_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('synonyymi_ibfk_1', type_='foreignkey')
        batch_op.drop_index('IDX_Synonyymi2')
        batch_op.drop_index('IDX_Synonyymi1')

    with op.batch_alter_table('suunniteltu_kasvupaikka', schema=None) as batch_op:
        batch_op.drop_constraint('suunniteltu_kasvupaikka_ibfk_1', type_='foreignkey')
        batch_op.drop_index('IDX_Suunniteltu_kasvupaikka1')

    with op.batch_alter_table('suomalainen_levinneisyysalue', schema=None) as batch_op:
        batch_op.drop_constraint('suomalainen_levinneisyysalue_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('suomalainen_levinneisyysalue_ibfk_2', type_='foreignkey')
        batch_op.drop_index('IDX_Suomalainen_Levinneisyysalue2')
        batch_op.drop_index('IDX_Suomalainen_Levinneisyysalue1')

    with op.batch_alter_table('suomalainen_kasvupaikka', schema=None) as batch_op:
        batch_op.drop_constraint('suomalainen_kasvupaikka_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('suomalainen_kasvupaikka_ibfk_1', type_='foreignkey')
        batch_op.drop_index('IDX_Suomalainen_kasvupaikka2')
        batch_op.drop_index('IDX_Suomalainen_kasvupaikka1')

    with op.batch_alter_table('sijoituspaikka', schema=None) as batch_op:
        batch_op.drop_constraint('sijoituspaikka_ibfk_1', type_='foreignkey')
        batch_op.drop_index('IDX_Sijoituspaikka1')

    with op.batch_alter_table('puutarhassa_viljelyn_tarkoitus', schema=None) as batch_op:
        batch_op.drop_constraint('puutarhassa_viljelyn_tarkoitus_ibfk_1', type_='foreignkey')
        batch_op.drop_index('IDX_Puutarhassa_viljelyn_tarkoitus1')
        batch_op.alter_column('viljely_nro',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('osastopaikka', schema=None) as batch_op:
        batch_op.drop_constraint('osastopaikka_ibfk_1', type_='foreignkey')
        batch_op.drop_index('IDX_Osastopaikka1')
        batch_op.alter_column('osaston_numero',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('naytetietoja', schema=None) as batch_op:
        batch_op.drop_constraint('naytetietoja_ibfk_1', type_='foreignkey')
        batch_op.drop_index('IDX_Naytetietoja1')
        batch_op.alter_column('uus_naytteen_paivays',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('naytetieto', schema=None) as batch_op:
        batch_op.drop_constraint('naytetieto_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('naytetieto_ibfk_2', type_='foreignkey')
        batch_op.drop_index('IDX_Naytetieto2')
        batch_op.drop_index('IDX_Naytetieto1')

    with op.batch_alter_table('muunkielinen_nimi', schema=None) as batch_op:
        batch_op.drop_constraint('muunkielinen_nimi_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('muunkielinen_nimi_ibfk_1', type_='foreignkey')
        batch_op.drop_index('IDX_Muunkielinen_nimi2')
        batch_op.drop_index('IDX_Muunkielinen_nimi1')

    with op.batch_alter_table('maaritysmerkinta', schema=None) as batch_op:
        batch_op.drop_constraint('maaritysmerkinta_ibfk_1', type_='foreignkey')
        batch_op.drop_index('IDX_Maaritysmerkinta1')
        batch_op.alter_column('uus_maarityspvm',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('maailman_levinneisyysalue', schema=None) as batch_op:
        batch_op.drop_constraint('maailman_levinneisyysalue_ibfk_1', type_='foreignkey')
        batch_op.drop_index('IDX_Maailman_Levinneisyysalue1')

    with op.batch_alter_table('lukitut_taulut', schema=None) as batch_op:
        batch_op.drop_index('avainkentta')

    with op.batch_alter_table('lahettaja', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('kayttajatiedot', schema=None) as batch_op:
        batch_op.drop_index('kayttajan_tunnus')

    with op.batch_alter_table('kasvin_kayttotarkoitus', schema=None) as batch_op:
        batch_op.drop_constraint('kasvin_kayttotarkoitus_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('kasvin_kayttotarkoitus_ibfk_2', type_='foreignkey')
        batch_op.drop_index('IDX_Kasvin_kayttotarkoitus2')
        batch_op.drop_index('IDX_Kasvin_kayttotarkoitus1')

    with op.batch_alter_table('kasvatustietoja', schema=None) as batch_op:
        batch_op.drop_constraint('kasvatustietoja_ibfk_1', type_='foreignkey')
        batch_op.drop_index('IDX_Kasvatustietoja1')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('kansainvaliset_sopimukset', schema=None) as batch_op:
        batch_op.drop_constraint('kansainvaliset_sopimukset_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('kansainvaliset_sopimukset_ibfk_1', type_='foreignkey')
        batch_op.drop_index('IDX_Kansainvaliset_Sopimukset2')
        batch_op.drop_index('IDX_Kansainvaliset_Sopimukset1')

    with op.batch_alter_table('hankintatiedot', schema=None) as batch_op:
        batch_op.drop_constraint('hankintatiedot_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('hankintatiedot_ibfk_1', type_='foreignkey')
        batch_op.drop_index('ix_hankintatiedot_hankintanumero')
        batch_op.drop_index('IDX_Hankintatiedot2')
        batch_op.drop_index('IDX_Hankintatiedot1')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('alkuperainen_kasvupaikka', schema=None) as batch_op:
        batch_op.drop_constraint('alkuperainen_kasvupaikka_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('alkuperainen_kasvupaikka_ibfk_1', type_='foreignkey')
        batch_op.drop_index('IDX_Alkuperainen_kasvupaikka2')
        batch_op.drop_index('IDX_Alkuperainen_kasvupaikka1')

    with op.batch_alter_table('alkuperaa_koskevat_tiedot', schema=None) as batch_op:
        batch_op.drop_constraint('alkuperaa_koskevat_tiedot_ibfk_1', type_='foreignkey')
        batch_op.drop_index('IDX_Alkuperaa_koskevat_tiedot1')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    op.create_table('_alembic_tmp_alkuperaa_koskevat_tiedot',
    sa.Column('alkupera_nro', sa.INTEGER(), nullable=False),
    sa.Column('alkuperatyyppi', sa.VARCHAR(length=255), nullable=True),
    sa.Column('maa', sa.VARCHAR(length=255), nullable=True),
    sa.Column('maan_ISOkoodi', sa.VARCHAR(length=255), nullable=True),
    sa.Column('alue', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ala_alue', sa.VARCHAR(length=255), nullable=True),
    sa.Column('kunta', sa.VARCHAR(length=255), nullable=True),
    sa.Column('kyla', sa.VARCHAR(length=255), nullable=True),
    sa.Column('latitude', sa.VARCHAR(length=255), nullable=True),
    sa.Column('longitude', sa.VARCHAR(length=255), nullable=True),
    sa.Column('grid_27_E', sa.VARCHAR(length=255), nullable=True),
    sa.Column('kasvupaikka', sa.VARCHAR(length=255), nullable=True),
    sa.Column('korkeus', sa.VARCHAR(length=255), nullable=True),
    sa.Column('keraaja', sa.VARCHAR(length=255), nullable=True),
    sa.Column('kerayspvm', sa.VARCHAR(length=255), nullable=True),
    sa.Column('keraysnumero', sa.VARCHAR(length=255), nullable=True),
    sa.Column('muita_keraystietoja', sa.TEXT(), nullable=True),
    sa.Column('keraysretki', sa.VARCHAR(length=255), nullable=True),
    sa.Column('hankintaID', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['hankintaID'], ['hankintatiedot.hankintaID'], name=op.f('alkuperaa_koskevat_tiedot_ibfk_1')),
    sa.PrimaryKeyConstraint('alkupera_nro')
    )
    # ### end Alembic commands ###
