"""Baseline migration

Revision ID: f8985dffebf3
Revises: 
Create Date: 2026-06-20 01:13:38.144059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8985dffebf3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_client_client_id'), table_name='oauth_client', if_exists=True)
    op.drop_index(op.f('ix_oauth_client_id'), table_name='oauth_client', if_exists=True)
    op.drop_table('oauth_client', if_exists=True)
    op.create_index('IDX_Alkuperaa_koskevat_tiedot1', 'alkuperaa_koskevat_tiedot', ['hankintaID'], unique=False)
    op.create_foreign_key('alkuperaa_koskevat_tiedot_ibfk_1', 'alkuperaa_koskevat_tiedot', 'hankintatiedot', ['hankintaID'], ['hankintaID'])
    op.create_index('IDX_Alkuperainen_kasvupaikka1', 'alkuperainen_kasvupaikka', ['taksonin_nro'], unique=False)
    op.create_index('IDX_Alkuperainen_kasvupaikka2', 'alkuperainen_kasvupaikka', ['viitenro'], unique=False)
    op.create_foreign_key('alkuperainen_kasvupaikka_ibfk_2', 'alkuperainen_kasvupaikka', 'viite', ['viitenro'], ['viitenro'])
    op.create_foreign_key('alkuperainen_kasvupaikka_ibfk_1', 'alkuperainen_kasvupaikka', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])
    op.create_index('IDX_Hankintatiedot1', 'hankintatiedot', ['taksonin_nro'], unique=False)
    op.create_index('IDX_Hankintatiedot2', 'hankintatiedot', ['lahettajanro'], unique=False)
    op.create_index('hankintanumero', 'hankintatiedot', ['hankintanumero'], unique=True)
    op.create_foreign_key('hankintatiedot_ibfk_1', 'hankintatiedot', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])
    op.create_foreign_key('hankintatiedot_ibfk_2', 'hankintatiedot', 'lahettaja', ['lahettajanro'], ['lahettajanro'])
    op.create_index('IDX_Kansainvaliset_Sopimukset1', 'kansainvaliset_sopimukset', ['taksonin_nro'], unique=False)
    op.create_index('IDX_Kansainvaliset_Sopimukset2', 'kansainvaliset_sopimukset', ['viitenro'], unique=False)
    op.create_foreign_key('kansainvaliset_sopimukset_ibfk_1', 'kansainvaliset_sopimukset', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])
    op.create_foreign_key('kansainvaliset_sopimukset_ibfk_2', 'kansainvaliset_sopimukset', 'viite', ['viitenro'], ['viitenro'])
    op.create_index('IDX_Kasvatustietoja1', 'kasvatustietoja', ['hankintaID'], unique=False)
    op.create_foreign_key('kasvatustietoja_ibfk_1', 'kasvatustietoja', 'hankintatiedot', ['hankintaID'], ['hankintaID'])
    op.create_index('IDX_Kasvin_kayttotarkoitus1', 'kasvin_kayttotarkoitus', ['taksonin_nro'], unique=False)
    op.create_index('IDX_Kasvin_kayttotarkoitus2', 'kasvin_kayttotarkoitus', ['viitenro'], unique=False)
    op.create_foreign_key('kasvin_kayttotarkoitus_ibfk_2', 'kasvin_kayttotarkoitus', 'viite', ['viitenro'], ['viitenro'])
    op.create_foreign_key('kasvin_kayttotarkoitus_ibfk_1', 'kasvin_kayttotarkoitus', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])
    op.create_index('kayttajan_tunnus', 'kayttajatiedot', ['kayttajan_tunnus'], unique=True)
    op.create_index('avainkentta', 'lukitut_taulut', ['avainkentta'], unique=True)
    op.create_index('IDX_Maailman_Levinneisyysalue1', 'maailman_levinneisyysalue', ['taksonin_nro'], unique=False)
    op.create_foreign_key('maailman_levinneisyysalue_ibfk_1', 'maailman_levinneisyysalue', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])
    op.alter_column('maaritysmerkinta', 'uus_maarityspvm',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=True)
    op.create_index('IDX_Maaritysmerkinta1', 'maaritysmerkinta', ['hankintaID'], unique=False)
    op.create_foreign_key('maaritysmerkinta_ibfk_1', 'maaritysmerkinta', 'hankintatiedot', ['hankintaID'], ['hankintaID'])
    op.create_index('IDX_Muunkielinen_nimi1', 'muunkielinen_nimi', ['taksonin_nro'], unique=False)
    op.create_index('IDX_Muunkielinen_nimi2', 'muunkielinen_nimi', ['viitenro'], unique=False)
    op.create_foreign_key('muunkielinen_nimi_ibfk_2', 'muunkielinen_nimi', 'viite', ['viitenro'], ['viitenro'])
    op.create_foreign_key('muunkielinen_nimi_ibfk_1', 'muunkielinen_nimi', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])
    op.create_index('IDX_Naytetieto1', 'naytetieto', ['taksonin_nro'], unique=False)
    op.create_index('IDX_Naytetieto2', 'naytetieto', ['viitenro'], unique=False)
    op.create_foreign_key('naytetieto_ibfk_1', 'naytetieto', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])
    op.create_foreign_key('naytetieto_ibfk_2', 'naytetieto', 'viite', ['viitenro'], ['viitenro'])
    op.alter_column('naytetietoja', 'uus_naytteen_paivays',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=True)
    op.create_index('IDX_Naytetietoja1', 'naytetietoja', ['hankintaID'], unique=False)
    op.create_foreign_key('naytetietoja_ibfk_1', 'naytetietoja', 'hankintatiedot', ['hankintaID'], ['hankintaID'])
    op.alter_column('osastopaikka', 'osaston_numero',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index('IDX_Osastopaikka1', 'osastopaikka', ['hankintaID'], unique=False)
    op.create_foreign_key('osastopaikka_ibfk_1', 'osastopaikka', 'hankintatiedot', ['hankintaID'], ['hankintaID'])
    op.alter_column('puutarhassa_viljelyn_tarkoitus', 'viljely_nro',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index('IDX_Puutarhassa_viljelyn_tarkoitus1', 'puutarhassa_viljelyn_tarkoitus', ['hankintaID'], unique=False)
    op.create_foreign_key('puutarhassa_viljelyn_tarkoitus_ibfk_1', 'puutarhassa_viljelyn_tarkoitus', 'hankintatiedot', ['hankintaID'], ['hankintaID'])
    op.create_index('IDX_Sijoituspaikka1', 'sijoituspaikka', ['osaston_numero'], unique=False)
    op.create_foreign_key('sijoituspaikka_ibfk_1', 'sijoituspaikka', 'osastopaikka', ['osaston_numero'], ['osaston_numero'])
    op.create_index('IDX_Suomalainen_kasvupaikka1', 'suomalainen_kasvupaikka', ['taksonin_nro'], unique=False)
    op.create_index('IDX_Suomalainen_kasvupaikka2', 'suomalainen_kasvupaikka', ['viitenro'], unique=False)
    op.create_foreign_key('suomalainen_kasvupaikka_ibfk_2', 'suomalainen_kasvupaikka', 'viite', ['viitenro'], ['viitenro'])
    op.create_foreign_key('suomalainen_kasvupaikka_ibfk_1', 'suomalainen_kasvupaikka', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])
    op.create_index('IDX_Suomalainen_Levinneisyysalue1', 'suomalainen_levinneisyysalue', ['taksonin_nro'], unique=False)
    op.create_index('IDX_Suomalainen_Levinneisyysalue2', 'suomalainen_levinneisyysalue', ['viitenro'], unique=False)
    op.create_foreign_key('suomalainen_levinneisyysalue_ibfk_1', 'suomalainen_levinneisyysalue', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])
    op.create_foreign_key('suomalainen_levinneisyysalue_ibfk_2', 'suomalainen_levinneisyysalue', 'viite', ['viitenro'], ['viitenro'])
    op.create_index('IDX_Suunniteltu_kasvupaikka1', 'suunniteltu_kasvupaikka', ['taksonin_nro'], unique=False)
    op.create_foreign_key('suunniteltu_kasvupaikka_ibfk_1', 'suunniteltu_kasvupaikka', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])
    op.create_index('IDX_Synonyymi1', 'synonyymi', ['taksonin_nro'], unique=False)
    op.create_index('IDX_Synonyymi2', 'synonyymi', ['viitenro'], unique=False)
    op.create_foreign_key('synonyymi_ibfk_2', 'synonyymi', 'viite', ['viitenro'], ['viitenro'])
    op.create_foreign_key('synonyymi_ibfk_1', 'synonyymi', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])
    op.create_index('IDX_Taksoni1', 'taksoni', ['jarjestysnumero'], unique=False)
    op.create_index('IDX_Taksoni2', 'taksoni', ['viitenro'], unique=False)
    op.create_foreign_key('taksoni_ibfk_1', 'taksoni', 'heimo', ['jarjestysnumero'], ['jarjestysnumero'])
    op.create_foreign_key('taksoni_ibfk_2', 'taksoni', 'viite', ['viitenro'], ['viitenro'])
    op.create_index('IDX_Taksonin_lappu1', 'taksonin_lappu', ['taksonin_nro'], unique=False)
    op.create_foreign_key('taksonin_lappu_ibfk_1', 'taksonin_lappu', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])
    op.create_index('IDX_Taksonin_viljelytiedot1', 'taksonin_viljelytiedot', ['taksonin_nro'], unique=False)
    op.create_foreign_key('taksonin_viljelytiedot_ibfk_1', 'taksonin_viljelytiedot', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])
    op.alter_column('tarkastusmerkinta', 'uus_tarkastuspvm',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index('IDX_Tarkastusmerkinta1', 'tarkastusmerkinta', ['sijoituspaikan_nro'], unique=False)
    op.create_foreign_key('tarkastusmerkinta_ibfk_1', 'tarkastusmerkinta', 'sijoituspaikka', ['sijoituspaikan_nro'], ['sijoituspaikan_nro'])
    op.alter_column('toimenpide', 'uus_pvm',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index('IDX_Toimenpide1', 'toimenpide', ['hankintaID'], unique=False)
    op.create_foreign_key('toimenpide_ibfk_1', 'toimenpide', 'hankintatiedot', ['hankintaID'], ['hankintaID'])
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index('IDX_Ymparistoindikaattoriluonne1', 'ymparistoindikaattoriluonne', ['taksonin_nro'], unique=False)
    op.create_index('IDX_Ymparistoindikaattoriluonne2', 'ymparistoindikaattoriluonne', ['viitenro'], unique=False)
    op.create_foreign_key('ymparistoindikaattoriluonne_ibfk_2', 'ymparistoindikaattoriluonne', 'viite', ['viitenro'], ['viitenro'])
    op.create_foreign_key('ymparistoindikaattoriluonne_ibfk_1', 'ymparistoindikaattoriluonne', 'taksoni', ['taksonin_nro'], ['taksonin_nro'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ymparistoindikaattoriluonne_ibfk_1', 'ymparistoindikaattoriluonne', type_='foreignkey')
    op.drop_constraint('ymparistoindikaattoriluonne_ibfk_2', 'ymparistoindikaattoriluonne', type_='foreignkey')
    op.drop_index('IDX_Ymparistoindikaattoriluonne2', table_name='ymparistoindikaattoriluonne')
    op.drop_index('IDX_Ymparistoindikaattoriluonne1', table_name='ymparistoindikaattoriluonne')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_constraint('toimenpide_ibfk_1', 'toimenpide', type_='foreignkey')
    op.drop_index('IDX_Toimenpide1', table_name='toimenpide')
    op.alter_column('toimenpide', 'uus_pvm',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('tarkastusmerkinta_ibfk_1', 'tarkastusmerkinta', type_='foreignkey')
    op.drop_index('IDX_Tarkastusmerkinta1', table_name='tarkastusmerkinta')
    op.alter_column('tarkastusmerkinta', 'uus_tarkastuspvm',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('taksonin_viljelytiedot_ibfk_1', 'taksonin_viljelytiedot', type_='foreignkey')
    op.drop_index('IDX_Taksonin_viljelytiedot1', table_name='taksonin_viljelytiedot')
    op.drop_constraint('taksonin_lappu_ibfk_1', 'taksonin_lappu', type_='foreignkey')
    op.drop_index('IDX_Taksonin_lappu1', table_name='taksonin_lappu')
    op.drop_constraint('taksoni_ibfk_2', 'taksoni', type_='foreignkey')
    op.drop_constraint('taksoni_ibfk_1', 'taksoni', type_='foreignkey')
    op.drop_index('IDX_Taksoni2', table_name='taksoni')
    op.drop_index('IDX_Taksoni1', table_name='taksoni')
    op.drop_constraint('synonyymi_ibfk_1', 'synonyymi', type_='foreignkey')
    op.drop_constraint('synonyymi_ibfk_2', 'synonyymi', type_='foreignkey')
    op.drop_index('IDX_Synonyymi2', table_name='synonyymi')
    op.drop_index('IDX_Synonyymi1', table_name='synonyymi')
    op.drop_constraint('suunniteltu_kasvupaikka_ibfk_1', 'suunniteltu_kasvupaikka', type_='foreignkey')
    op.drop_index('IDX_Suunniteltu_kasvupaikka1', table_name='suunniteltu_kasvupaikka')
    op.drop_constraint('suomalainen_levinneisyysalue_ibfk_2', 'suomalainen_levinneisyysalue', type_='foreignkey')
    op.drop_constraint('suomalainen_levinneisyysalue_ibfk_1', 'suomalainen_levinneisyysalue', type_='foreignkey')
    op.drop_index('IDX_Suomalainen_Levinneisyysalue2', table_name='suomalainen_levinneisyysalue')
    op.drop_index('IDX_Suomalainen_Levinneisyysalue1', table_name='suomalainen_levinneisyysalue')
    op.drop_constraint('suomalainen_kasvupaikka_ibfk_1', 'suomalainen_kasvupaikka', type_='foreignkey')
    op.drop_constraint('suomalainen_kasvupaikka_ibfk_2', 'suomalainen_kasvupaikka', type_='foreignkey')
    op.drop_index('IDX_Suomalainen_kasvupaikka2', table_name='suomalainen_kasvupaikka')
    op.drop_index('IDX_Suomalainen_kasvupaikka1', table_name='suomalainen_kasvupaikka')
    op.drop_constraint('sijoituspaikka_ibfk_1', 'sijoituspaikka', type_='foreignkey')
    op.drop_index('IDX_Sijoituspaikka1', table_name='sijoituspaikka')
    op.drop_constraint('puutarhassa_viljelyn_tarkoitus_ibfk_1', 'puutarhassa_viljelyn_tarkoitus', type_='foreignkey')
    op.drop_index('IDX_Puutarhassa_viljelyn_tarkoitus1', table_name='puutarhassa_viljelyn_tarkoitus')
    op.alter_column('puutarhassa_viljelyn_tarkoitus', 'viljely_nro',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_constraint('osastopaikka_ibfk_1', 'osastopaikka', type_='foreignkey')
    op.drop_index('IDX_Osastopaikka1', table_name='osastopaikka')
    op.alter_column('osastopaikka', 'osaston_numero',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_constraint('naytetietoja_ibfk_1', 'naytetietoja', type_='foreignkey')
    op.drop_index('IDX_Naytetietoja1', table_name='naytetietoja')
    op.alter_column('naytetietoja', 'uus_naytteen_paivays',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('naytetieto_ibfk_2', 'naytetieto', type_='foreignkey')
    op.drop_constraint('naytetieto_ibfk_1', 'naytetieto', type_='foreignkey')
    op.drop_index('IDX_Naytetieto2', table_name='naytetieto')
    op.drop_index('IDX_Naytetieto1', table_name='naytetieto')
    op.drop_constraint('muunkielinen_nimi_ibfk_1', 'muunkielinen_nimi', type_='foreignkey')
    op.drop_constraint('muunkielinen_nimi_ibfk_2', 'muunkielinen_nimi', type_='foreignkey')
    op.drop_index('IDX_Muunkielinen_nimi2', table_name='muunkielinen_nimi')
    op.drop_index('IDX_Muunkielinen_nimi1', table_name='muunkielinen_nimi')
    op.drop_constraint('maaritysmerkinta_ibfk_1', 'maaritysmerkinta', type_='foreignkey')
    op.drop_index('IDX_Maaritysmerkinta1', table_name='maaritysmerkinta')
    op.alter_column('maaritysmerkinta', 'uus_maarityspvm',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('maailman_levinneisyysalue_ibfk_1', 'maailman_levinneisyysalue', type_='foreignkey')
    op.drop_index('IDX_Maailman_Levinneisyysalue1', table_name='maailman_levinneisyysalue')
    op.drop_index('avainkentta', table_name='lukitut_taulut')
    op.drop_index('kayttajan_tunnus', table_name='kayttajatiedot')
    op.drop_constraint('kasvin_kayttotarkoitus_ibfk_1', 'kasvin_kayttotarkoitus', type_='foreignkey')
    op.drop_constraint('kasvin_kayttotarkoitus_ibfk_2', 'kasvin_kayttotarkoitus', type_='foreignkey')
    op.drop_index('IDX_Kasvin_kayttotarkoitus2', table_name='kasvin_kayttotarkoitus')
    op.drop_index('IDX_Kasvin_kayttotarkoitus1', table_name='kasvin_kayttotarkoitus')
    op.drop_constraint('kasvatustietoja_ibfk_1', 'kasvatustietoja', type_='foreignkey')
    op.drop_index('IDX_Kasvatustietoja1', table_name='kasvatustietoja')
    op.drop_constraint('kansainvaliset_sopimukset_ibfk_2', 'kansainvaliset_sopimukset', type_='foreignkey')
    op.drop_constraint('kansainvaliset_sopimukset_ibfk_1', 'kansainvaliset_sopimukset', type_='foreignkey')
    op.drop_index('IDX_Kansainvaliset_Sopimukset2', table_name='kansainvaliset_sopimukset')
    op.drop_index('IDX_Kansainvaliset_Sopimukset1', table_name='kansainvaliset_sopimukset')
    op.drop_constraint('hankintatiedot_ibfk_2', 'hankintatiedot', type_='foreignkey')
    op.drop_constraint('hankintatiedot_ibfk_1', 'hankintatiedot', type_='foreignkey')
    op.drop_index('hankintanumero', table_name='hankintatiedot')
    op.drop_index('IDX_Hankintatiedot2', table_name='hankintatiedot')
    op.drop_index('IDX_Hankintatiedot1', table_name='hankintatiedot')
    op.drop_constraint('alkuperainen_kasvupaikka_ibfk_1', 'alkuperainen_kasvupaikka', type_='foreignkey')
    op.drop_constraint('alkuperainen_kasvupaikka_ibfk_2', 'alkuperainen_kasvupaikka', type_='foreignkey')
    op.drop_index('IDX_Alkuperainen_kasvupaikka2', table_name='alkuperainen_kasvupaikka')
    op.drop_index('IDX_Alkuperainen_kasvupaikka1', table_name='alkuperainen_kasvupaikka')
    op.drop_constraint('alkuperaa_koskevat_tiedot_ibfk_1', 'alkuperaa_koskevat_tiedot', type_='foreignkey')
    op.drop_index('IDX_Alkuperaa_koskevat_tiedot1', table_name='alkuperaa_koskevat_tiedot')
    op.create_table('oauth_client',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('hashed_secret', sa.VARCHAR(length=255), nullable=False),
    sa.Column('redirect_uris', sa.TEXT(), nullable=False),
    sa.Column('scopes', sa.VARCHAR(length=255), server_default=sa.text("('')"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_client_id'), 'oauth_client', ['id'], unique=False)
    op.create_index(op.f('ix_oauth_client_client_id'), 'oauth_client', ['client_id'], unique=1)
    # ### end Alembic commands ###
